# China Patent CN111038740A: Spherical Electromagnetic Antigravity Drone

**Patent Number:** CN111038740A
**Title:** Unconventional Spacecraft Propulsion Systems (spherical electromagnetic antigravity drone)
**Assignee:** Chinese nuclear scientist; awarded by CCP
**Filed:** 2020 (published 2020)
**Jurisdiction:** China (foreign)
**Source:** [patents.google.com/patent/CN111038740A/en](https://patents.google.com/patent/CN111038740A/en)
**Track Directory (Physics_Math):** 1_Track/ — rotating ring coil array generating MHD body force; directly relevant to Attempt 1 rotating EM field geometry

**Image files:**
- `patents_intl/tweets/raw_download/1924157772335132986_1.png`
- `patents_intl/tweets/raw_download/1924157772335132986_2.png`

## Overview

The two patent diagrams for CN111038740A reveal a spherical vehicle whose propulsion is generated entirely by electromagnetic induction acting on a ring array of permanent or electromagnets embedded in the craft's equatorial belt. The cross-section (Figure 1 in the images, labeled components 1–22) shows the outer spherical shell (1) enclosing a central axial solenoid stack (3/4) flanked by two concentric annular bands of individual magnet coils (5, 6, 7, 8) arranged circumferentially around the sphere's interior at two latitudinal positions. Each band carries coils whose field axes are oriented radially outward from the vehicle axis, producing a combined toroidal magnetic field configuration when driven in sequence.

The second diagram (Figure 2 in the patent images) shows the same cross-section with the coils represented as standard electrical winding symbols (cross for current-into-page, dot for current-out-of-page), confirming that adjacent coils in the ring carry opposing current phases to produce a rotating magnetic field. The central solenoid (3) provides a primary axial field B_z that interacts with the rotating azimuthal field B_φ generated by the ring coils. The interaction of these two field components produces a net Lorentz body force density f = J × B throughout the plasma or ionized medium induced around the craft exterior, or alternatively acting on the craft structure itself if the coil array is driven against an external magnetic reference.

## Physics Mechanism

The physics claimed sits at the intersection of magnetohydrodynamics (MHD) and rotating-field electromagnetic propulsion. In conventional MHD drives, a conducting fluid (plasma or electrolyte) is subjected to crossed electric and magnetic fields, producing a J × B body force that accelerates the fluid and by reaction drives the vehicle — the principle of the submarine MHD drive patented under US3322374A in 1967 and experimentally demonstrated in Japan's Yamato-1 vessel (1992). CN111038740A applies the same principle but to an aerial/space vehicle using induced atmospheric plasma as the conducting medium. When the annular coil arrays spin the magnetic field pattern at angular velocity ω, free electrons and ions in the surrounding air are accelerated azimuthally. At sufficient field strength the ionization threshold of air is crossed locally, generating the plasma sheath required for sustained MHD coupling.

The critical parameters governing thrust magnitude are: applied magnetic field strength B (tesla), coil ring radius r, number of pole pairs p, the conductivity σ of the induced plasma, and the velocity differential between rotating field and plasma rotation. Thrust scales approximately as:

F ~ σ(v_field − v_plasma)B²r²L

where L is the axial extent of the active region. For meaningful thrust against gravity — lifting a multi-kilogram drone — the required field strengths at modest plasma conductivities (σ ~ 10–100 S/m for weakly ionized air) imply B values of order 1–10 T across the active zone, achievable with superconducting coil stacks but challenging with room-temperature electromagnets at compact scales.

## Strategic and Engineering Significance

The patent's assignee is identified as a Chinese nuclear scientist who received CCP state awards, strongly suggesting a national defense research context. The classification within "unconventional spacecraft propulsion systems" (the same IPC B64G1/409 category as multiple US Navy and Russian patents) is notable. CN111038740A was filed in 2020 and is an active patent; it received patent citations indicating it was not filed as a purely academic disclosure but as protectable IP.

What the patent accomplishes concretely: it discloses a specific internal architecture (ring coil arrangement, coil count, axial solenoid geometry, circuit topology) that enables omnidirectional field steering by independently varying current phase and magnitude in each coil. Unlike a fixed-axis MHD thruster, the proposed design can redirect the rotating field axis in any direction by suitable phasing, giving the craft vectored thrust control without mechanical gimbals. This is architecturally equivalent to the three-axis field control used in brushless motor design scaled up to vehicle propulsion, and it provides a direct engineering path to the omnidirectional, instantaneous-maneuver flight characteristics documented in Navy UAP sensor data.

The craft's spherical geometry is not incidental to the propulsion design. A sphere maximizes the ratio of surface area (where EM coupling occurs) to volume (where electronics and payload reside), and it presents a constant cross-section to the induced plasma regardless of flight direction. The plasma sheath that forms under operation would absorb and scatter radar microwave frequencies, providing inherent stealth characteristics — consistent with observed radar return signatures of UAP spherical objects.

The limitation of the patent as disclosed is that it provides no thermal management specification for the power electronics driving multi-tesla coil arrays, and no energy source is identified for sustained operation. The power requirement for the described geometry at useful thrust levels is estimated in the multi-megawatt range, requiring an onboard power source far beyond conventional battery or fuel-cell technology. This is consistent with the thesis that operational versions of such craft require a classified energy source — zero-point field extraction, compact fusion, or a recovered exotic power system — that would not appear in the patent filing.

The cross-match between CN111038740A's structural diagrams and reported spherical UAP objects is striking: the equatorial bulge created by the coil ring assembly produces the characteristic oblate spheroid or "smooth ball with slight equatorial band" appearance reported in multiple military UAP encounters.

## Sources

- [CN111038740A on Google Patents](https://patents.google.com/patent/CN111038740A/en)
- US3322374A (1967) — foundational MHD propulsion patent
- Yamato-1 MHD submarine demonstration, Japan, 1992

*This information was compiled from Break_thrus.mdx staging file.*
