# United States Patent US10135366B2: Electromagnetic Field Generator — Piezoelectric Ferroelectric Shell (US Navy / Salvatore Pais)

**Patent Number:** US10135366B2
**Title:** Electromagnetic Field Generator and Method to Generate an Electromagnetic Field
**Inventor:** Salvatore Cezar Pais
**Assignee:** US Department of Navy
**Filed:** July 24, 2015; Granted November 20, 2018
**Status:** Expired - Fee Related (adjusted expiration 2037-08-15)
**Classification:** H02N11/002 — Generators
**Jurisdiction:** United States (US)
**Track Directory (Physics_Math):** Track_3/ — piezoelectric ferroelectric ceramic shell vibrating at high frequency under electrostatic charge; power and field-generation source for US10144532B2 mass reduction cavity; ZPF coupling mechanism

**Image files:**
- `patents_intl/tweets/raw_download/2043660831695556647_2.jpg`

## Abstract

"The electromagnetic field generator includes a shell, an electrostatic generator, a power plant, a thermoelectric generator, and an electric motor. The shell has embedded polycrystalline ferroelectric ceramic material which is polarized such that the ceramic material exhibits strong Piezoelectric Effect properties thus inducing high frequency vibrations. The shell may be further doped with radioactive elements which under high frequency vibrations induce gamma ray emission. The electrostatic generator is for charging up the shell and is disposed within the shell. The power plant is to generate thermal power, and is disposed within the sphere. The thermoelectric generator is to convert the thermal power generated by the power plant to electrical energy. The electric motor powered by the electrical energy generated by the thermoelectric generator, and supplies input voltage such that the shell spins at high angular speeds, vibrates at high frequencies, and generates an electromagnetic field."

## Structural Description

The three patent figures show a cross-section of a spherical shell with layered internal components: the PZT-type polycrystalline ferroelectric ceramic shell surrounding an electrostatic generator, an internal power plant (unspecified thermally — deliberately left vague, consistent with a compact fission or fusion source), and a thermoelectric conversion stage. Alternative configurations in Figures 2 and 3 show different geometric arrangements of the same functional components.

## Physics Mechanism: High-Q Piezoelectric Resonance at High Electrostatic Charge

The piezoelectric ferroelectric ceramic shell (lead zirconate titanate, PZT, or similar PLZT composition) converts electrical input to mechanical strain and vice versa. When driven at mechanical resonance frequencies (kilohertz to megahertz range depending on shell geometry and material), the shell develops very large surface mechanical oscillation amplitudes relative to the input power — a quality factor (Q) enhancement. Simultaneously, the electrostatic generator charges the shell to high potential.

The combination of high-Q mechanical vibration at high electrostatic charge produces, according to Pais's claim, electromagnetic field strengths far exceeding what conventional antenna or magnetic systems can generate at comparable power levels.

## Piezonuclear Effects: Radioactive Doping Claim

The radioactive doping provision — optionally adding radioactive isotopes to the PZT ceramic — is the most unconventional claim. The stated effect is that high-frequency mechanical vibration of a radioactive-doped crystal lattice induces gamma ray emission. This is not consistent with standard nuclear physics, where gamma emission depends on nuclear transition energetics independent of mechanical state.

However, piezonuclear effects — nuclear reaction rate modification by extreme mechanical compression of crystalline materials — have been claimed in controversial Italian physics experiments (Cardone et al., 2009–2012). If real, the gamma emission would provide an additional high-energy electromagnetic source collocated with the vibrating shell, potentially amplifying the "Pais Effect" on the local ZPF.

## System Integration with US10144532B2

This device is the power and field-generation source that feeds US10144532B2's resonant cavity (Track_20). Together, the two patents form a complete system:

- **US10135366B2** (this patent) — generates the extreme high-frequency EM field via the vibrating charged piezoelectric shell
- **US10144532B2** (Track_20) — routes the EM field into the resonant cavity structure to polarize the vacuum and achieve mass reduction

The integrated system diagram:

```
[Thermoelectric Generator] ← [Power Plant (unspecified)]
         ↓
[Electric Motor]
         ↓
[Spinning PZT Shell] ← [Electrostatic Generator]
         ↓ (high-frequency EM field)
[Resonant Cavity — US10144532B2]
         ↓ (polarized vacuum outside outer wall)
[Inertial Mass Reduction]
```

## Sources

- [US10135366B2 on Google Patents](https://patents.google.com/patent/US10135366B2)
- US10144532B2 — companion mass reduction craft patent (Track_20)
- Cardone, F. et al. (2009–2012) — piezonuclear effects, controversial Italian physics experiments
- Haisch, B., Rueda, A., and Puthoff, H.E. (1994) — ZPF-inertia framework

*This information was compiled from Break_thrus.mdx staging file.*
